---
- name: Install Keepalived
  yum:
    name: keepalived
    state: present

- name: Enable and configure firewall for VRRP
  firewalld:
    rich_rule: 'rule protocol value="vrrp" accept'
    permanent: yes
    state: enabled
    immediate: yes
  when: firewalld_state != 'stopped'
  ignore_errors: yes

- name: Configure Keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart keepalived

- name: Enable and start Keepalived service
  systemd:
    name: keepalived
    enabled: yes
    state: started

- name: Configure SELinux for Keepalived
  seboolean:
    name: keepalived_connect_any
    state: yes
    persistent: yes
  when: selinux_state != 'disabled'
  ignore_errors: yes
